name: OAI Error Reporter

on:
  workflow_call:
    inputs:
      job_name:
        description: 'The name of the job to inspect for failures.'
        required: true
        type: string
      model:
        description: 'The AI model to use for analysis.'
        required: true
        type: string
      endpoint:
        description: 'The API endpoint for OpenWebUI.'
        required: true
        type: string
      issue_label:
        description: 'Labels to add to the created GitHub issue.'
        required: false
        default: 'ci-failure'
        type: string
    secrets:
      OPENWEBUI_API_KEY:
        description: 'The API key for OpenWebUI.'
        required: true

permissions:
  issues: write
  actions: read
  contents: read

jobs:
  report_errors:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Fetch Failed Steps
      - name: Fetch Failed Steps
        id: fetch_failures
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const jobName = '${{ inputs.job_name }}';
            const runId = context.runId;
            const { data: jobs } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });

            const targetJob = jobs.jobs.find(job => job.name === jobName);

            if (!targetJob) {
              throw new Error(`Job "${jobName}" not found.`);
            }

            const failedSteps = targetJob.steps.filter(step => step.conclusion === 'failure');

            if (failedSteps.length === 0) {
              core.info(`No failed steps found in job "${jobName}".`);
              return { failures: '' };
            }

            let summary = '';
            failedSteps.forEach(step => {
              summary += `- **${step.name}**: ${step.conclusion}\n`;
            });

            core.setOutput('failures', summary);

      # Step 2: Send Errors to OpenWebUI and Get Analysis
      - name: Send Errors to OpenWebUI and Get Analysis
        id: bot_response
        if: steps.fetch_failures.outputs.failures != ''
        run: |
          echo "Sending errors to OpenWebUI..."

          # Ensure jq is installed
          if ! command -v jq &> /dev/null
          then
              echo "jq could not be found. Installing..."
              sudo apt-get update && sudo apt-get install -y jq
          fi

          # Prepare the JSON payload using inputs
          PAYLOAD=$(jq -n \
            --arg model "${{ inputs.model }}" \
            --arg content "The following steps have failed in the job \"${{ inputs.job_name }}\":\n${{ steps.fetch_failures.outputs.failures }}\n\nPlease analyze these errors and provide recommendations." \
            '{
              model: $model,
              messages: [
                {
                  role: "user",
                  content: $content
                }
              ]
            }')

          # Send the POST request and capture the response
          RESPONSE=$(curl -s -X POST "${{ inputs.endpoint }}" \
            -H "Authorization: Bearer ${{ secrets.OPENWEBUI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")

          echo "Response from OpenWebUI: $RESPONSE"

          # Extract the bot's message using jq
          BOT_MESSAGE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

          echo "Bot's analysis: $BOT_MESSAGE"

          # Set the bot's message as an output
          echo "analysis=$BOT_MESSAGE" >> $GITHUB_OUTPUT

      # Step 3: Create GitHub Issue with Bot's Analysis
      - name: Create GitHub Issue with Analysis
        if: steps.bot_response.outputs.analysis != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const analysis = `\`\`\`
            ${{ steps.bot_response.outputs.analysis }}
            \`\`\``;
            const failures = `\`\`\`
            ${{ steps.fetch_failures.outputs.failures }}
            \`\`\``;
            const issueTitle = "⚠️ CI Pipeline Failures Detected";
            const issueBody = `
            **CI Pipeline Failures Summary:**
            ${failures}

            **Bot Analysis and Recommendations:**
            ${analysis}

            **Workflow Run Details:**
            - Repository: \`${context.repo.owner}/${context.repo.repo}\`
            - Workflow: \`${context.workflow}\`
            - Run ID: \`${context.runId}\`
            - Run URL: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}

            Please review the failures and follow the bot's recommendations to resolve the issues.
            `;

            // Check if an issue with the same title already exists
            const { data: existingIssues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['${{ inputs.issue_label }}'],
            });

            const issueExists = existingIssues.some(issue => issue.title === issueTitle);

            if (!issueExists) {
              await github.rest.issues.create({
                owner,
                repo,
                title: issueTitle,
                body: issueBody,
                labels: ['${{ inputs.issue_label }}']
              });
              console.log("GitHub issue with bot analysis created successfully.");
            } else {
              console.log("An issue for CI failures already exists.");
            }
    ```

### Key Changes:

1. **Defining `api_key` as a Secret:**
   - In the `workflow_call` inputs, remove `api_key` and define it under `secrets` as `OPENWEBUI_API_KEY`.

2. **Accessing `api_key` Securely:**
   - In the `Send Errors to OpenWebUI and Get Analysis` step, access the `api_key` using `${{ secrets.OPENWEBUI_API_KEY }}` instead of `inputs.api_key`.

3. **Removing `api_key` from Inputs:**
   - By defining `api_key` as a secret, we avoid exposing it as an input, enhancing security.

4. **Permissions:**
   - The `permissions` block grants the necessary permissions without overstepping. Ensure these are adequate for your use case.

---

## 4. Updating the Primary Workflow

With the reusable workflow updated to accept `api_key` as a secret (`OPENWEBUI_API_KEY`), you need to adjust your primary workflow (`tester.yaml`) to pass the secret correctly via the `secrets:` block instead of the `with:` block.

### Correcting the `report_errors` Job

**Original `report_errors` Job:**

```yaml
report_errors:
  needs: manifests
  if: failure()
  uses: freeletics/actions/.github/workflows/oai-error-reporter.yaml@main
  with:
    job_name: "manifests"
    model: "qwen2.5:0.5b"
    endpoint: "https://oai-int.freeletics.com/api/chat/completions"
    api_key: "${{ secrets.OAI_INT_GITHUB_CI_API_KEY }}"
    issue_label: "ci-failure"
